version: '3.4'

networks:
  bdr-network:
    driver: bridge

services:
  bdr.web:
    container_name: bdr.web
    image: registry.gitlab.com/bk2t/bdr:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;
      - ConnectionStrings__Default=mongodb://bdr.mongo/BankDataReporting
      - App__SelfUrl=http://localhost
      - AuthServer__Authority=http://localhost
    build:
      context: .
      dockerfile: src/BK2T.BankDataReporting.Web/Dockerfile
    ports:
      - "5000:80"
    networks:
      - bdr-network
    depends_on:
      - "bdr.mongo"
    volumes:
      - ~/.aspnet/https:/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  bdr.mongo:
    container_name: bdr.mongo
    image: mongo:5.0
    restart: always
    networks:
      - bdr-network
    volumes:
      - './data:/data/db'